#include <stddef.h>
#include <stdint.h>

#include "interrupts.h"
#include "../../io/printf.h"
#include<debug/debug.h>

void (*interrupt_handlers[256])(struct interrupt_frame* frame);

static void
dump_interrupt_frame(const struct interrupt_frame* frame)
{
    kprintf("Interrupt Frame Dump:\n");
    kprintf("  Segment:            %016lx\n", frame->segment);
    kprintf("  General Purpose Registers:\n");
    kprintf("    RDI:              %016lx\n", frame->rdi);
    kprintf("    RSI:              %016lx\n", frame->rsi);
    kprintf("    RBP:              %016lx\n", frame->rbp);
    kprintf("    RBX:              %016lx\n", frame->rbx);
    kprintf("    RDX:              %016lx\n", frame->rdx);
    kprintf("    RCX:              %016lx\n", frame->rcx);
    kprintf("    RAX:              %016lx\n", frame->rax);
    kprintf("    R8:               %016lx\n", frame->r8);
    kprintf("    R9:               %016lx\n", frame->r9);
    kprintf("    R10:              %016lx\n", frame->r10);
    kprintf("    R11:              %016lx\n", frame->r11);
    kprintf("    R12:              %016lx\n", frame->r12);
    kprintf("    R13:              %016lx\n", frame->r13);
    kprintf("    R14:              %016lx\n", frame->r14);
    kprintf("    R15:              %016lx\n", frame->r15);
    kprintf("  Interrupt Number:   %016lx\n", frame->interrupt_number);
    kprintf("  Error Code:         %016lx\n", frame->error_code);
    kprintf("  RIP:                %016lx\n", frame->rip);
    kprintf("  CS:                 %016lx\n", frame->cs);
    kprintf("  RFLAGS:             %016lx\n", frame->rflags);
    kprintf("  RSP:                %016lx\n", frame->rsp);
    kprintf("  SS:                 %016lx\n", frame->ss);
    kprintf("\n");
}

void
register_interrupt_handler(const uint8_t vector, void (*isr)(struct interrupt_frame* frame))
{
    interrupt_handlers[vector] = isr;
}

void
interrupt_handler(struct interrupt_frame* frame)
{
    /* Call the associated handler for the interrupt vector if it exists */
    if (interrupt_handlers[frame->interrupt_number] != NULL) {
        interrupt_handlers[frame->interrupt_number](frame);

    /* >= 32 means it is an external/user defined interrupt */
    } else if (frame->interrupt_number >= 32) {
        kprintf("======Unhandled Interrupt: %d======\n", frame->interrupt_number);
        dump_interrupt_frame(frame);

    /* < 32 means it is an exception (probably generated by the cpu) */
    } else {
        kprintf("======Unhandled Exception: %d======\n", frame->interrupt_number);
        dump_interrupt_frame(frame);
        for (;;) {
            asm("nop");
        }
    }
}
